//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macabresoft.Macabre2D.Framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macabresoft.Macabre2D.Framework.Licenses", typeof(Licenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///All Rights Reserved
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvaloniaUI {
            get {
                return ResourceManager.GetString("AvaloniaUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2020 Microsoft Corporation
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fluent_UI_System_Icons {
            get {
                return ResourceManager.GetString("Fluent UI System Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Definitions.
        ///
        ///&quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///distribution as defined by Sections 1 through 9 of this document.
        ///
        ///&quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///owner that is granting the License.
        ///
        ///&quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///that co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FluentAssertions {
            get {
                return ResourceManager.GetString("FluentAssertions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2016 Macabresoft, Brett Story
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Macabre2D {
            get {
                return ResourceManager.GetString("Macabre2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2020 Macabresoft
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Macabresoft_Core {
            get {
                return ResourceManager.GetString("Macabresoft.Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICROSOFT SOFTWARE LICENSE TERMS
        ///
        ///MICROSOFT .NET LIBRARY
        ///
        ///These license terms are an agreement between you and Microsoft Corporation (or based on where you live, one of its affiliates). They apply to the software named above. The terms also apply to any Microsoft services or updates for the software, except to the extent those have different terms.
        ///
        ///IF YOU COMPLY WITH THESE LICENSE TERMS, YOU HAVE THE RIGHTS BELOW.
        ///
        ///1.    INSTALLATION AND USE RIGHTS.
        ///You may install and use any number of copies of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_NET_Test_Sdk {
            get {
                return ResourceManager.GetString("Microsoft.NET.Test.Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2008 - 2015 Jb Evain
        ///Copyright (c) 2008 - 2011 Novell, Inc.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining
        ///a copy of this software and associated documentation files (the
        ///&quot;Software&quot;), to deal in the Software without restriction, including
        ///without limitation the rights to use, copy, modify, merge, publish,
        ///distribute, sublicense, and/or sell copies of the Software, and to
        ///permit persons to whom the Software is furnished to do so, subject to
        ///the following conditi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mono_Cecil {
            get {
                return ResourceManager.GetString("Mono.Cecil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///Portions Copyright © The Mono.Xna Team
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mono_Xna {
            get {
                return ResourceManager.GetString("Mono.Xna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿Microsoft Public License (Ms-PL)
        ///MonoGame - Copyright © 2009-2021 The MonoGame Team
        ///
        ///All rights reserved.
        ///
        ///This license governs use of the accompanying software. If you use the software,
        ///you accept this license. If you do not accept the license, do not use the
        ///software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot;
        ///have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonoGame {
            get {
                return ResourceManager.GetString("MonoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Newtonsoft_Json {
            get {
                return ResourceManager.GetString("Newtonsoft.Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2009 Anthony Egerton (nsubstitute@delfish.com) and David Tchepak (dave@davesquared.net)
        ///All rights reserved.
        /// 
        ///Redistribution and use in source and binary forms, with or without modification,
        ///are permitted provided that the following conditions are met:
        /// 
        ///    * Redistributions of source code must retain the above copyright notice,
        ///    this list of conditions and the following disclaimer.
        ///    * Redistributions in binary form must reproduce the above copyright notice,
        ///    this list of c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NSubstitute {
            get {
                return ResourceManager.GetString("NSubstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2021 Charlie Poole, Rob Prouse
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright not [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUnit {
            get {
                return ResourceManager.GetString("NUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2011-2021 Charlie Poole, 2014-2021 Terje Sandstrom
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUnit3TestAdapter {
            get {
                return ResourceManager.GetString("NUnit3TestAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                  Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unity {
            get {
                return ResourceManager.GetString("Unity", resourceCulture);
            }
        }
    }
}
