//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macabre2D.Framework {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licenses {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licenses() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Macabre2D.Framework.Licenses", typeof(Licenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Macabre2D {
            get {
                return ResourceManager.GetString("Macabre2D", resourceCulture);
            }
        }
        
        internal static string MonoGame {
            get {
                return ResourceManager.GetString("MonoGame", resourceCulture);
            }
        }
        
        internal static string Fluent_UI_System_Icons {
            get {
                return ResourceManager.GetString("Fluent UI System Icons", resourceCulture);
            }
        }
        
        internal static string Macabresoft_Core {
            get {
                return ResourceManager.GetString("Macabresoft.Core", resourceCulture);
            }
        }
        
        internal static string Newtonsoft_Json {
            get {
                return ResourceManager.GetString("Newtonsoft.Json", resourceCulture);
            }
        }
        
        internal static string AvaloniaUI {
            get {
                return ResourceManager.GetString("AvaloniaUI", resourceCulture);
            }
        }
        
        internal static string AwesomeAssertions {
            get {
                return ResourceManager.GetString("AwesomeAssertions", resourceCulture);
            }
        }
        
        internal static string Microsoft_NET_Test_Sdk {
            get {
                return ResourceManager.GetString("Microsoft.NET.Test.Sdk", resourceCulture);
            }
        }
        
        internal static string NSubstitute {
            get {
                return ResourceManager.GetString("NSubstitute", resourceCulture);
            }
        }
        
        internal static string NUnit {
            get {
                return ResourceManager.GetString("NUnit", resourceCulture);
            }
        }
        
        internal static string NUnit3TestAdapter {
            get {
                return ResourceManager.GetString("NUnit3TestAdapter", resourceCulture);
            }
        }
        
        internal static string Unity {
            get {
                return ResourceManager.GetString("Unity", resourceCulture);
            }
        }
        
        internal static string Microsoft__NET_Library {
            get {
                return ResourceManager.GetString("Microsoft .NET Library", resourceCulture);
            }
        }
        
        internal static string NuGet {
            get {
                return ResourceManager.GetString("NuGet", resourceCulture);
            }
        }
        
        internal static string ReactiveUI {
            get {
                return ResourceManager.GetString("ReactiveUI", resourceCulture);
            }
        }
        
        internal static string Public_Sans {
            get {
                return ResourceManager.GetString("Public Sans", resourceCulture);
            }
        }
    }
}
